### ISSUE TITLE
The Agent model used in the paper

### ISSUE THREAD

**Issue by khai-meetkai** [apple/ToolSandbox#1]
Thank you for your great work, I just wonder what is the agent **model** used in your evaluation result reported in the paper?
Is it **GPT_4_o_2024_05_13** ?
![Screen Shot 2024-08-16 at 10 13 19](https://github.com/user-attachments/assets/122356f6-6bb7-491f-bf93-08523c7074bd)

**Comment by jiarui-lu2** [comment]
Thanks @khai-meetkai! The list of agent models evaluated is a listed in the left column of the table. The user simulator used is `GPT_4_o_2024_05_13`. For more information, checkout the role registries here: https://github.com/apple/ToolSandbox/blob/1a1dc83bd84948f0a3d3ace0e59923fc760c111b/tool_sandbox/cli/utils.py#L65-L101

**Comment by khai-meetkai** [comment]
@jiarui-lu2 Thank you!
