### ISSUE TITLE
Dataset is not released

### ISSUE THREAD

**Issue by Dandelionym** [apple/ToolSandbox#5]
Dear authors, really excellent work you have done! In order to reproduce the work, I may need the `full dataset` for the inference. However, I didn’t find the data in this repo.   So may I ask `whether the data will be released soon?` Besides, is that possible to show simple scripts as examples? Really thanks for your publishing the impressive work!

Best, 
Mellen

**Comment by jiarui-lu2** [comment]
Hi @Dandelionym, since this is a dynamic evaluation environment, the test cases are defined as python objects instead of a static serializable file. You can find the test cases defined in https://github.com/apple/ToolSandbox/tree/main/tool_sandbox/scenarios
